use std::path::{Path, PathBuf};

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(out_dir).join("collatz_kernels.rs");
    let kernel_crate = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../kernels/collatz");

    // No `.kernel(...)` declaration any more — the host-side
    // launch wrapper is generated by the `#[claspr::kernel]`
    // proc-macro on the stub in `tests/end_to_end.rs`. The build
    // script's job here is just compiling the kernel crate to SPIR-V
    // and emitting the raw `Kernels` struct (untyped fields).
    claspr_build::compile(&kernel_crate)
        .opencl12()
        .write_to(&out_path)
        .expect("compile collatz kernel");
}
