//! Heterogeneous parallel composition — [`Bundle2`] through [`Bundle16`]
//! plus the [`bundle!`](crate::bundle!) macro.
//!
//! Where [`AndThen`](crate::AndThen) is sequential, `Bundle` is
//! parallel: the child ops have no data dependency between them. Their
//! `execute` calls happen in declaration order from the host's POV but
//! land on the chain's out-of-order queue, so the OpenCL runtime is
//! free to overlap them on the device.
//!
//! Arities 2..=16 are generated by `impl_bundle!` below. For more
//! arity, lift to [`fan_out`](crate::fan_out()) (homogeneous) or chain
//! `Bundle`s together.
//!
//! ## Examples
//!
//! ```ignore
//! use claspr_async::{DeviceOperation, bundle, value};
//!
//! let (a, b) = bundle!(value(1u32), value(2u32)).sync(&ctx)?;
//! assert_eq!((a, b), (1, 2));
//!
//! let (a, b, c) = bundle!(op_a, op_b, op_c).sync(&ctx)?;
//! ```

use crate::exec_ctx::ExecutionContext;
use crate::device_op::{Deps, DeviceOperation, wrap_event};
use crate::{Error, Launcher, Result};

/// Implementation detail — generates `BundleN` + a constructor function
/// + a `DeviceOperation` impl for each arity.
macro_rules! impl_bundle {
    ($name:ident, $ctor:ident, $($field:ident : $ty:ident),+) => {
        #[doc = concat!(
            "Heterogeneous bundle of independent device ops. Built by ",
            "[`bundle!`](crate::bundle!) at this arity.",
        )]
        pub struct $name<$($ty),+> {
            $(pub(crate) $field: $ty),+
        }

        #[doc = concat!("Construct a [`", stringify!($name), "`].")]
        // Arity comes from the bundle! macro arms; high-arity bundles
        // legitimately need many arguments. Suppress here so users
        // don't hit it transitively at every `bundle!(...)` call site.
        #[allow(clippy::too_many_arguments)]
        pub fn $ctor<$($ty),+>($($field: $ty),+) -> $name<$($ty),+>
        where
            $($ty: DeviceOperation),+
        {
            $name { $($field),+ }
        }

        impl<$($ty),+> DeviceOperation for $name<$($ty),+>
        where
            $($ty: DeviceOperation),+
        {
            type Output = ($(<$ty as DeviceOperation>::Output),+,);

            fn execute(
                self,
                ctx: &ExecutionContext<'_>,
                deps: Deps,
            ) -> Result<(Self::Output, Deps)> {
                // Each child gets a clone of the input deps — no
                // inter-child ordering — so the OOO runtime can
                // overlap them on the device.
                //
                // Hold every child's events in `child_evts` until after
                // the marker enqueue: the marker uses raw cl_event
                // handles, and dropping the Arcs before the enqueue
                // could (in principle) release the underlying events
                // out from under it. The runtime keeps its own retain
                // on in-flight events but the spec doesn't strictly
                // guarantee it — keep our refs alive to be safe.
                let mut child_evts: Vec<Deps> = Vec::new();
                let outputs = (
                    $({
                        let (out, evts) =
                            self.$field.execute(ctx, deps.clone())?;
                        child_evts.push(evts);
                        out
                    }),+,
                );
                let all_events: Vec<opencl3::types::cl_event> = child_evts
                    .iter()
                    .flat_map(|evts| evts.iter().map(|d| d.as_ref().get()))
                    .collect();
                // SAFETY: empty or non-empty wait-list; cl_event handles
                // are valid (held by `child_evts` Arcs).
                let marker = unsafe {
                    ctx.cl_queue().enqueue_marker_with_wait_list(&all_events)
                }.map_err(Error::OpenCl)?;
                // `child_evts` drops here — safe, the marker is enqueued.
                drop(child_evts);
                Ok((outputs, vec![wrap_event(marker)]))
            }
        }
    };
}

impl_bundle!(Bundle2, bundle2, a: A, b: B);
impl_bundle!(Bundle3, bundle3, a: A, b: B, c: C);
impl_bundle!(Bundle4, bundle4, a: A, b: B, c: C, d: D);
impl_bundle!(Bundle5, bundle5, a: A, b: B, c: C, d: D, e: E);
impl_bundle!(Bundle6, bundle6, a: A, b: B, c: C, d: D, e: E, f: F);
impl_bundle!(Bundle7, bundle7, a: A, b: B, c: C, d: D, e: E, f: F, g: G);
impl_bundle!(Bundle8, bundle8, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H);
impl_bundle!(Bundle9, bundle9, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I);
impl_bundle!(Bundle10, bundle10, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J);
impl_bundle!(Bundle11, bundle11, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K);
impl_bundle!(Bundle12, bundle12, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L);
impl_bundle!(Bundle13, bundle13, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M);
impl_bundle!(Bundle14, bundle14, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N);
impl_bundle!(Bundle15, bundle15, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O);
impl_bundle!(Bundle16, bundle16, a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P);

/// Variadic constructor for [`Bundle2`] through [`Bundle16`]. Picks
/// the right `BundleN` based on the number of arguments.
///
/// ```ignore
/// let (a, b) = bundle!(op_a, op_b).sync(&ctx)?;
/// let (a, b, c) = bundle!(op_a, op_b, op_c).sync(&ctx)?;
/// // ... up to 16 children
/// ```
#[macro_export]
macro_rules! bundle {
    ($a:expr, $b:expr $(,)?) => {
        $crate::bundle::bundle2($a, $b)
    };
    ($a:expr, $b:expr, $c:expr $(,)?) => {
        $crate::bundle::bundle3($a, $b, $c)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr $(,)?) => {
        $crate::bundle::bundle4($a, $b, $c, $d)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr $(,)?) => {
        $crate::bundle::bundle5($a, $b, $c, $d, $e)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr $(,)?) => {
        $crate::bundle::bundle6($a, $b, $c, $d, $e, $f)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr $(,)?) => {
        $crate::bundle::bundle7($a, $b, $c, $d, $e, $f, $g)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr $(,)?) => {
        $crate::bundle::bundle8($a, $b, $c, $d, $e, $f, $g, $h)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr $(,)?) => {
        $crate::bundle::bundle9($a, $b, $c, $d, $e, $f, $g, $h, $i)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr $(,)?) => {
        $crate::bundle::bundle10($a, $b, $c, $d, $e, $f, $g, $h, $i, $j)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr $(,)?) => {
        $crate::bundle::bundle11($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr, $l:expr $(,)?) => {
        $crate::bundle::bundle12($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr, $l:expr, $m:expr $(,)?) => {
        $crate::bundle::bundle13($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $m)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr, $l:expr, $m:expr, $n:expr $(,)?) => {
        $crate::bundle::bundle14($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $m, $n)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr, $l:expr, $m:expr, $n:expr, $o:expr $(,)?) => {
        $crate::bundle::bundle15($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $m, $n, $o)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $i:expr, $j:expr, $k:expr, $l:expr, $m:expr, $n:expr, $o:expr, $p:expr $(,)?) => {
        $crate::bundle::bundle16(
            $a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $m, $n, $o, $p,
        )
    };
}
