//! Proc-macro frontend for [claspr] — write a kernel function once
//! with kernel-style attributes and signature, get a host-side launch
//! wrapper for free.
//!
//! ## Generated shape
//!
//! For each `#[claspr::kernel] fn foo(...)`, the macro emits a single
//! method `Kernels::foo(grid, slice_by_value, scalar)` that returns a
//! per-kernel `Op` struct. The Op works in two modes:
//!
//! - **Tier 1 (sync, explicit launcher):** `.wait(launcher) -> Output`
//!   or `.submit(launcher) -> (Output, Event)`. Modifiers: `.after(ev)`,
//!   `.after_all(events)`, `.profiled(cb)`.
//! - **Tier 2 (async chain):** the Op implements `DeviceOperation`,
//!   so it composes into `.and_then` / `bundle!` / `fan_out` chains.
//!
//! `Output` is the slice arg(s) the kernel touches — bare for one
//! slice, tuple for many, `()` for none. Scalars are dropped from
//! `Output`. The same single method serves both contexts.
//!
//! ## Example
//!
//! ```ignore
//! mod kernels {
//!     include!(concat!(env!("OUT_DIR"), "/collatz_kernels.rs"));
//! }
//!
//! // Stub mirrors the kernel signature exactly. Body is discarded
//! // by the proc-macro; leave it empty or copy-paste the real kernel
//! // body for documentation / future single-source extraction.
//! #[claspr::kernel]
//! fn collatz_kernel(
//!     #[spirv(global_invocation_id)] _id: USizeVec3,
//!     #[spirv(cross_workgroup)] data: &mut [u32],
//! ) {}
//!
//! fn main() -> claspr::Result<()> {
//!     let ctx = claspr::Context::any()?;
//!     let kernels = kernels::Kernels::load(&ctx)?;
//!     let mut data: Vec<u32> = (1..=1024).collect();
//!     let mut buf = claspr::DeviceSlice::alloc_zero(&ctx, data.len())?;
//!     buf.write(&data).wait(&ctx)?;
//!     // Tier 1: slices move in, come back out of `.wait()`.
//!     let buf = kernels.collatz_kernel([data.len()], buf).wait(&ctx)?;
//!     buf.read(&mut data).wait(&ctx)?;
//!     Ok(())
//! }
//! ```
//!
//! ## In an async chain
//!
//! ```ignore
//! use claspr_async::{download, upload, DeviceOperation};
//!
//! let result: Vec<u32> = upload!(initial_data)
//!     .and_then(|buf| kernels.fill_u32([N], buf, 5))
//!     .and_then(|buf| kernels.scale_u32([N], buf, 3))
//!     .and_then(|buf| download!(buf))
//!     .sync(&ctx)?;
//! ```
//!
//! [claspr]: https://github.com/bricevideau-ai/claspr

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{
    Attribute, FnArg, Ident, ItemFn, Pat, PatType, Path, Signature, Token, Type, TypeMacro,
    TypeReference, TypeSlice, Visibility, parse_macro_input, spanned::Spanned,
};

/// Mark a function as a claspr kernel — generates a host-side launch
/// wrapper.
///
/// See the crate-level docs for the rough shape; behaviour follows
/// these rules when walking the stub's parameters:
///
/// - A parameter with a `#[spirv(<builtin>)]` attribute (anything except
///   `cross_workgroup` or no attribute) is **dropped** — these are
///   SPIR-V built-in inputs filled in by the OpenCL runtime, not
///   host-side arguments.
/// - A parameter `#[spirv(cross_workgroup)] name: &mut [T]` or `&[T]`
///   is **translated** to `name: ::claspr::DeviceSlice<T>` (owned by
///   the emitted Op; flows through `Output`).
/// - A parameter `&Image!(...)` is translated to `::claspr::Image2D<A, F>`
///   (also owned and threaded through `Output`).
/// - Any other parameter is passed through verbatim — used for scalar
///   `T` arguments via the `claspr::scalar_arg!`-emitted `KernelArg`
///   impl. Scalars do *not* flow through `Output`.
#[proc_macro_attribute]
pub fn kernel(attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let attr_args = match parse_attr_args(attr) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error().into(),
    };
    match expand_kernel(&func, &attr_args) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Mark a function **or a module** as device-side code — included in
/// the kernel sub-crate generated by `claspr_build::compile_from_host`,
/// otherwise a no-op on the host beyond suppressing dead-code warnings.
///
/// On a **function**, signals to the build script that this helper
/// should be copied into the kernel crate alongside the
/// `#[claspr::kernel]`-marked entry points that call it. The macro
/// adds `#[allow(dead_code)]` so the host doesn't warn when only the
/// kernel-side compilation actually uses the function.
///
/// On a **module**, the macro does *two* things:
///
/// 1. Lifts the whole module body into the generated kernel crate at
///    build time — every `use`, `const`, `static`, helper `fn`, type
///    def, even nested modules.
/// 2. Appends two items **inside** the module body for the host build:
///    `include!(concat!(env!("OUT_DIR"), "/kernels.rs"));` (which
///    pulls in the build-script-generated `Kernels` struct and
///    `Kernels::load`) and a `pub fn kernels(ctx: &Context) -> Result<Kernels>`
///    convenience wrapper. Calling code reads `gpu::kernels(&ctx)?`,
///    and `#[claspr::kernel]` defaults to targeting `Kernels` —
///    relative to where the macro is invoked, which is inside the
///    same module.
///
/// Because each `#[claspr::device]` module owns its own `Kernels`
/// struct and `kernels()` function, multiple device modules can sit
/// in the same file without colliding (they live in different
/// module-namespaces).
///
/// The build script must write to `OUT_DIR/<modname>.rs` for step 2
/// to find the generated module — `claspr_build::compile_from_host(...).write()`
/// derives the filename from each `#[claspr::device] mod <name>` it
/// discovers, so the coupling matches automatically.
///
/// ```ignore
/// #[claspr::device]
/// mod gpu {
///     use spirv_std::cl::Float3;
///     pub const RADIUS: f32 = 0.9;
///
///     pub fn helper(p: Float3) -> f32 { /* shared host+device helper */ }
///
///     #[claspr::kernel] // defaults to `kernels = Kernels` (in scope here)
///     pub fn raymarch(/* ... */) { /* uses RADIUS, helper, etc. */ }
/// }
///
/// // host code:
/// let kernels = gpu::kernels(&ctx)?;
/// kernels.raymarch(&ctx, /* ... */)?;
/// ```
///
/// Items at the same scope as the device module that aren't tagged
/// `#[claspr::kernel]` or `#[claspr::device]` are host-only —
/// `claspr-build` skips them when generating the kernel crate, so
/// things like `use claspr::*` and `fn main()` work normally.
#[proc_macro_attribute]
pub fn device(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let item_ts: TokenStream2 = item.into();
    // Parse to decide between the fn form and the mod form.
    let parsed: syn::Result<syn::Item> = syn::parse2(item_ts.clone());
    if let Ok(syn::Item::Mod(mut item_mod)) = parsed {
        if let Some((_, items)) = &mut item_mod.content {
            // Append the include and the convenience `kernels()` fn
            // *inside* the user's module body. Filename matches the
            // module name so multiple `#[claspr::device]` modules in
            // the same file don't share output (build script writes
            // `OUT_DIR/<modname>.rs` per device module). Order
            // doesn't matter for type/method resolution within a
            // module — the impl blocks emitted by `#[claspr::kernel]`
            // (also inside this module) find `Kernels` regardless of
            // where the include lands.
            let mod_filename = format!("/{}.rs", item_mod.ident);
            let include_item: syn::Item = syn::parse_quote! {
                include!(concat!(env!("OUT_DIR"), #mod_filename));
            };
            let kernels_fn: syn::Item = syn::parse_quote! {
                /// Build the program from the embedded SPIR-V and look up every entry point.
                ///
                /// Thin wrapper around `Kernels::load_from(ctx, SPV_BYTES)` —
                /// the same `load_from` that any `claspr::kernels!`-generated
                /// `Kernels` exposes — so `#[claspr::device]` consumes the
                /// public abstraction rather than its own one-off path.
                pub fn kernels(ctx: &::claspr::Context) -> ::claspr::Result<Kernels> {
                    Kernels::load_from(ctx, SPV_BYTES)
                }
            };
            items.push(include_item);
            items.push(kernels_fn);
        }
        let body = quote! { #item_mod };
        return quote! {
            #[allow(dead_code, unused_imports)]
            #body
        }
        .into();
    }
    // Function form (or anything else): same `#[allow(...)]` wrap as
    // before. `unused_imports` is in there because a device module's
    // `use` statements often look unused on the host (the kernel
    // body that uses them is discarded by `#[claspr::kernel]`).
    quote! {
        #[allow(dead_code, unused_imports)]
        #item_ts
    }
    .into()
}

/// Declare a host-side `Kernels` surface from a list of kernel
/// signatures, decoupled from how the SPIR-V was produced or where
/// it lives.
///
/// ```ignore
/// claspr::kernels! {
///     pub mod gpu {
///         fn fill(#[spirv(global_invocation_id)] _id: spirv_std::glam::USizeVec3,
///                 #[spirv(cross_workgroup)] data: &mut [u32],
///                 value: u32);
///         fn scale(#[spirv(global_invocation_id)] _id: spirv_std::glam::USizeVec3,
///                  #[spirv(cross_workgroup)] data: &mut [u32],
///                  factor: u32);
///     }
/// }
///
/// // Then at runtime, supply SPIR-V from anywhere:
/// let kernels = gpu::Kernels::load_from(&ctx, &std::fs::read("kernel.spv")?)?;
/// // or
/// let kernels = gpu::Kernels::load_from(&ctx, EMBEDDED_SPV_BYTES)?;
/// kernels.fill([1024], buf, 42).wait(&ctx)?;
/// ```
///
/// ## Shape
///
/// Each `fn name(args...);` inside the module body is treated as if
/// it were `#[claspr::kernel] fn name(args...) {}` — same parameter
/// classification (slice/image/scalar/builtin), same generated `Op`
/// struct, same Tier 1 (`.wait`/`.submit`) + Tier 2
/// (`DeviceOperation` via the blanket on `claspr::KernelOp`) shape.
///
/// The macro emits a module with:
///
/// - `pub struct Kernels { __claspr_program: ::claspr::Program }`
/// - `Kernels::bind(program)` — takes an already-built program, validates entries.
/// - `Kernels::load_from(ctx, spv)` — builds a program from `&[u8]` then binds.
/// - `Kernels::kernel(name)` — escape hatch for an untyped `cl_kernel`.
/// - Per-fn typed launchers + their hidden `Op` modules.
///
/// Unlike the `Kernels` struct generated by [`compile_from_host`] in
/// build scripts, `kernels!` does **not** embed any SPIR-V. The
/// caller picks the SPIR-V source — `include_bytes!`,
/// `std::fs::read`, downloaded blob, anything `&[u8]`.
///
/// ## Relationship to `#[claspr::device]`
///
/// `#[claspr::device]` is sugar for the single-source case: the
/// kernel sources, the build-script-emitted `SPV_BYTES`, and a
/// `kernels(&ctx)` convenience function all sit in one module.
/// Internally that convenience function is just
/// `Kernels::load_from(ctx, SPV_BYTES)` — the same constructor
/// `kernels!`-defined surfaces expose.
///
/// [`compile_from_host`]: https://docs.rs/claspr-build
#[proc_macro]
pub fn kernels(input: TokenStream) -> TokenStream {
    let parsed = parse_macro_input!(input as KernelsMacroInput);
    match expand_kernels(parsed) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// `pub mod <ident> { fn sig1(...); fn sig2(...); ... }`
struct KernelsMacroInput {
    vis: Visibility,
    mod_ident: Ident,
    sigs: Vec<Signature>,
}

impl syn::parse::Parse for KernelsMacroInput {
    fn parse(input: syn::parse::ParseStream<'_>) -> syn::Result<Self> {
        let vis = input.parse::<Visibility>()?;
        let _mod_kw = input.parse::<Token![mod]>()?;
        let mod_ident = input.parse::<Ident>()?;
        let body;
        syn::braced!(body in input);
        let mut sigs = Vec::new();
        while !body.is_empty() {
            // Allow but ignore any outer doc/attr lines preceding a
            // signature so users can document their kernels.
            let _attrs = body.call(Attribute::parse_outer)?;
            let sig: Signature = body.parse()?;
            let _semi = body.parse::<Token![;]>()?;
            sigs.push(sig);
        }
        Ok(Self {
            vis,
            mod_ident,
            sigs,
        })
    }
}

fn expand_kernels(input: KernelsMacroInput) -> syn::Result<TokenStream2> {
    let vis = &input.vis;
    let mod_ident = &input.mod_ident;

    // Per-fn launchers. Synthesize an empty-body ItemFn from each
    // signature so we can reuse `expand_kernel` verbatim — same
    // classifier, same emitted Op shape, zero drift between
    // `#[claspr::kernel]` and `kernels!`.
    //
    // `args.kernels = Kernels` (relative path) resolves to the local
    // `Kernels` struct emitted below, exactly like `#[claspr::device]`
    // mod usage does.
    let attr_args = AttrArgs {
        kernels: syn::parse_quote!(Kernels),
    };
    let mut launchers: Vec<TokenStream2> = Vec::with_capacity(input.sigs.len());
    let mut entry_names: Vec<String> = Vec::with_capacity(input.sigs.len());
    for sig in input.sigs {
        entry_names.push(sig.ident.to_string());
        // Force `pub` on each emitted launcher so the typed methods
        // are reachable from outside the `mod_ident` module. Users
        // can't easily set per-fn vis on a `fn sig();` line anyway.
        let func = ItemFn {
            attrs: Vec::new(),
            vis: syn::parse_quote!(pub),
            sig,
            block: Box::new(syn::parse_quote!({})),
        };
        launchers.push(expand_kernel(&func, &attr_args)?);
    }

    // Module body: Kernels struct + impl with bind/load_from/kernel,
    // followed by all the per-fn launchers (each contributes an
    // `impl Kernels { fn name(...) }` block plus a hidden Op submod).
    Ok(quote! {
        #[allow(dead_code, unused_imports, non_snake_case, non_camel_case_types)]
        #vis mod #mod_ident {
            /// Host-side typed view over a SPIR-V module. Bound to a
            /// runtime [`::claspr::Program`] via [`Self::bind`] or
            /// [`Self::load_from`]; SPIR-V bytes can come from
            /// anywhere — `include_bytes!`, `std::fs::read`, a
            /// downloaded blob.
            pub struct Kernels {
                #[doc(hidden)]
                pub __claspr_program: ::claspr::Program,
                #[doc(hidden)]
                pub __claspr_ctx: ::claspr::Context,
            }

            impl Kernels {
                /// Take ownership of an already-built program and
                /// validate every typed launcher's entry-point name
                /// resolves. Returns Err if any name is missing from
                /// the program.
                ///
                /// Takes the program by value because opencl3's
                /// `Program` is not `Clone`. The `ctx` arg is stored
                /// alongside so every launched Op carries it for the
                /// no-arg `.wait()` / `.submit()` terminals.
                pub fn bind(
                    ctx: &::claspr::Context,
                    program: ::claspr::Program,
                ) -> ::claspr::Result<Self> {
                    // Validate every typed launcher's entry point by
                    // attempting one `clCreateKernel` per name. The
                    // names are the launcher idents, expanded at
                    // macro time below.
                    for ep in Self::ENTRY_POINTS {
                        let _ = ::claspr::Kernel::create(&program, ep)?;
                    }
                    ::core::result::Result::Ok(Self {
                        __claspr_program: program,
                        __claspr_ctx: ::core::clone::Clone::clone(ctx),
                    })
                }

                /// Build a program from `spv` and bind every entry
                /// point. Takes the SPIR-V bytes from any source —
                /// `include_bytes!`, a file read at runtime, a
                /// downloaded blob, anything `&[u8]`.
                pub fn load_from(
                    ctx: &::claspr::Context,
                    spv: &[u8],
                ) -> ::claspr::Result<Self> {
                    Self::bind(ctx, ctx.build_program(spv)?)
                }

                /// Get a fresh `cl_kernel` handle for `name`. Panics
                /// if the runtime is out of resources — `bind` /
                /// `load_from` validated every entry point's
                /// existence, so the only remaining failure mode is
                /// OOM. Used internally by the typed launchers;
                /// exposed for the rare untyped-launch case.
                pub fn kernel(&self, name: &str) -> ::claspr::Kernel {
                    ::claspr::Kernel::create(&self.__claspr_program, name)
                        .unwrap_or_else(|e| panic!("clCreateKernel({name:?}) failed: {e:?}"))
                }

                /// The kernel entry-point names this `Kernels` view
                /// expects to find in the program. Built from the
                /// `fn` idents in the `kernels!` invocation.
                pub const ENTRY_POINTS: &'static [&'static str] = &[
                    #( #entry_names ),*
                ];
            }

            #( #launchers )*
        }
    })
}

struct AttrArgs {
    /// Path to the build-script-generated `Kernels` struct that this
    /// kernel's typed launch method will be added to.
    kernels: Path,
}

fn parse_attr_args(attr: TokenStream) -> syn::Result<AttrArgs> {
    let mut kernels: Option<Path> = None;
    let parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("kernels") {
            kernels = Some(meta.value()?.parse::<Path>()?);
            Ok(())
        } else {
            Err(meta.error(
                "unsupported claspr::kernel argument; expected `kernels = path::to::Kernels`",
            ))
        }
    });
    syn::parse::Parser::parse(parser, attr)?;
    // Default to `Kernels` (relative path) — `#[claspr::device]` on
    // a module includes the generated `Kernels` struct at the end of
    // the module body, so a `#[claspr::kernel]` invocation inside
    // that module resolves `Kernels` to the local one. Override
    // with `kernels = path::to::Other` when you want to attach the
    // launch method to a different generated `Kernels` (e.g. a
    // second device module in the same crate, or kernels declared
    // outside any device module).
    let kernels = kernels.unwrap_or_else(|| syn::parse_quote!(Kernels));
    Ok(AttrArgs { kernels })
}

fn expand_kernel(func: &ItemFn, args: &AttrArgs) -> syn::Result<TokenStream2> {
    let vis = &func.vis;
    let name = &func.sig.ident;

    // Per-host-param accumulators. The single emitted method takes
    // slices by value (so they can flow through Tier 2 chains and so
    // Tier 1 terminals can return them back). Scalars are by-value.
    // `op_arg_pass` is what we hand to LaunchOp::new from inside the
    // terminal / execute: `&name` for slices/images, `name` for scalars.
    //
    // Slices get one fresh generic type parameter each
    // (`__claspr_D0`, `__claspr_D1`, …) bounded
    // `: ::claspr::KernelSliceArg<elem>`. This lets the same emitted
    // method accept `DeviceSlice<T>`, `MappedSlice<T>`, or
    // `USMSlice<T>` interchangeably while keeping the flow-through
    // Output typed precisely.
    //
    // Images get *two* fresh generics each — a format generic
    // `__claspr_F0` bounded
    // `: ::claspr::image::format::Format<SampledFamily = <K>>` and
    // an image generic `__claspr_I0` bounded
    // `: ::claspr::KernelImage<dim>D<Access>Arg<<K>>`. `<K>` is the
    // sampled-type-family marker derived from the kernel's `type=`
    // keyword (`type=u32` → `Uint`, `i32` → `Sint`, `f32` → `Float`).
    // `<Access>` is `Read`, `Write`, or `ReadWrite` based on the
    // kernel-side `&`/`&mut` mutability + optional
    // `#[spirv(image_access = "...")]` override. The two generics
    // together let the same wrapper method accept any
    // `Image<dim>D<A, F>` with matching access marker + matching
    // sampled-family — e.g. a `type=u32` kernel accepts
    // `Image2D<ReadOnly, R8G8B8A8Uint>`, `Image2D<ReadOnly, R32Uint>`,
    // `Image2D<ReadOnly, R32G32B32A32Uint>` etc. interchangeably,
    // and the wrapper flows the user's concrete type through to
    // Output without coercion.
    let mut host_names: Vec<TokenStream2> = Vec::new();
    // How each arg is stored into the Op's `args` field at construction:
    // slices wrap via `ToInput::to_input()` (→ `Input<__D>`), scalars verbatim.
    // Distinct from `host_names` (the destructure pattern at enqueue).
    let mut op_field_init: Vec<TokenStream2> = Vec::new();
    // Per-slice resolution stmts run after the enqueue destructure: rebind each
    // slice's `Input<__D>` to a concrete buffer (`.resolve_concrete()?`). A pipe
    // here is unreachable on the Tier-1 path (errors clearly if it ever isn't).
    let mut input_resolve: Vec<TokenStream2> = Vec::new();
    // Extra generics that live ONLY on the kernel METHOD signature, not on the
    // Op struct/impls: the per-slice `__claspr_S{n}: ToInput<elem, Buf=__D{n}>`
    // input generics. The Op is generic over `__D{n}` only (it stores
    // `Input<__D>`), so these would be "unused type parameter" errors there.
    let mut method_only_generics: Vec<(TokenStream2, TokenStream2)> = Vec::new();
    let mut method_params: Vec<TokenStream2> = Vec::new();
    let mut arg_types: Vec<TokenStream2> = Vec::new();
    let mut op_arg_pass: Vec<TokenStream2> = Vec::new();
    let mut output_names: Vec<TokenStream2> = Vec::new();
    let mut output_types: Vec<TokenStream2> = Vec::new();
    // `(generic_ident, bound_token_stream)` — populated once per
    // slice param + twice per image param, in source order. Drives
    // the `<__claspr_D0, __claspr_F0, __claspr_I0, ...>` +
    // `where`-equivalent inline bounds on every emitted impl block.
    let mut generics: Vec<(TokenStream2, TokenStream2)> = Vec::new();
    // Per-kind counters so the `__claspr_D{n}` / `__claspr_F{n}` /
    // `__claspr_I{n}` names stay stable per slice/image regardless
    // of interleaving with other param kinds.
    let mut slice_gen_idx = 0usize;
    let mut image_gen_idx = 0usize;

    for input in &func.sig.inputs {
        let FnArg::Typed(pt) = input else {
            return Err(syn::Error::new(
                input.span(),
                "claspr::kernel does not accept `self` parameters",
            ));
        };
        match classify_param(pt)? {
            ParamRole::Builtin => continue,
            ParamRole::Slice {
                name: pname,
                elem,
                mutable,
            } => {
                // Two generics per slice:
                //   __claspr_D{n} — the concrete BUFFER type (flows to Output,
                //     bounded by the read/read-write slice trait).
                //   __claspr_I{n} — the METHOD ARG, `ToInput<elem, Buf=__D>`,
                //     so it accepts a concrete buffer OR a `Pipe` of one with
                //     __D inferred (no turbofish). The Op stores `Input<__D>`.
                let gid = quote::format_ident!("__claspr_D{}", slice_gen_idx);
                let sid = quote::format_ident!("__claspr_S{}", slice_gen_idx);
                slice_gen_idx += 1;
                let gid_tt: TokenStream2 = quote! { #gid };
                let iid_tt: TokenStream2 = quote! { #sid };
                // Buffer bound by mutability: `&[T]` → KernelSliceReadArg<T>;
                // `&mut [T]` → KernelSliceReadWriteArg<T> (also KernelWritable,
                // excluding ReadOnly / Frozen at the type level).
                let dbound: TokenStream2 = if mutable {
                    quote! { #gid: ::claspr::KernelSliceReadWriteArg<#elem> }
                } else {
                    quote! { #gid: ::claspr::KernelSliceReadArg<#elem> }
                };
                let ibound: TokenStream2 =
                    quote! { #sid: ::claspr::ToInput<#elem, Buf = #gid> };
                generics.push((gid_tt.clone(), dbound));
                method_only_generics.push((iid_tt.clone(), ibound));

                host_names.push(pname.clone());
                // Method takes the `ToInput` arg; the Op stores `Input<__D>`.
                method_params.push(quote! { #pname: #iid_tt });
                arg_types.push(quote! { ::claspr::Input<#gid_tt> });
                op_field_init.push(quote! { ::claspr::ToInput::to_input(#pname) });
                // Tier-1 enqueue: resolve the `Input` to a concrete buffer,
                // then pass it by ref to LaunchOp (same as before).
                input_resolve.push(quote! {
                    let #pname = ::claspr::Input::resolve_concrete(#pname)?;
                });
                op_arg_pass.push(quote! { &#pname });
                output_names.push(pname.clone());
                output_types.push(gid_tt);
            }
            ParamRole::Image {
                name: pname,
                dim,
                family,
                access_segment,
            } => {
                // One fresh generic per image param: the image
                // generic, constrained to the matching
                // `KernelImage<dim>D<Access>Arg<family>` trait. The
                // family marker (`Uint`/`Sint`/`Float`) is a
                // concrete type, not a generic — the runtime trait
                // impls pick the right one based on the format `F`
                // inside the user's `Image<dim>D<A, F>` via F's
                // `SampledFamily` associated type. No separate
                // `__claspr_F` generic is needed; that was an
                // earlier shape that introduced an unused type
                // parameter on the emitted Op struct.
                let iid = quote::format_ident!("__claspr_I{}", image_gen_idx);
                image_gen_idx += 1;
                let iid_tt: TokenStream2 = quote! { #iid };

                let trait_name = quote::format_ident!("KernelImage{}{}Arg", dim, access_segment);

                generics.push((
                    iid_tt.clone(),
                    quote! { #iid: ::claspr::#trait_name<#family> },
                ));

                host_names.push(pname.clone());
                method_params.push(quote! { #pname: #iid_tt });
                arg_types.push(iid_tt.clone());
                op_field_init.push(quote! { #pname });
                op_arg_pass.push(quote! { &#pname });
                output_names.push(pname.clone());
                output_types.push(iid_tt);
            }
            ParamRole::Scalar { name: pname, ty } => {
                host_names.push(pname.clone());
                method_params.push(quote! { #pname: #ty });
                arg_types.push(ty);
                op_field_init.push(quote! { #pname });
                op_arg_pass.push(quote! { #pname });
            }
        }
    }

    // Generic parameter forms used in `impl<...>` / `Op<...>` / fn
    // signature positions. Three flavours:
    //   `<__D0, __D1>`              — for use sites where the generics
    //                                  are already-bound (Op<__D0, __D1>).
    //   `<__D0: K..., __D1: K...>`  — for declarator positions (impl
    //                                  blocks, method generic lists).
    //   `(empty)`                   — when there are no slice params.
    let gen_decl: TokenStream2 = if generics.is_empty() {
        quote! {}
    } else {
        let bounds = generics.iter().map(|(_, b)| b);
        quote! { < #( #bounds ),* > }
    };
    let gen_use: TokenStream2 = if generics.is_empty() {
        quote! {}
    } else {
        let ids = generics.iter().map(|(id, _)| id);
        quote! { < #( #ids ),* > }
    };

    // The kernel METHOD's generic decl = Op generics (`__D{n}`) PLUS the
    // method-only input generics (`__S{n}: ToInput<…>`). The Op struct/impls
    // use only `gen_decl`/`gen_use` (the `__D`s); the `__S`s appear solely in
    // the method signature, where they constrain the args and pin each
    // `__D{n}` via `Buf = __D{n}`.
    let method_gen_decl: TokenStream2 = {
        let all: Vec<&TokenStream2> = generics
            .iter()
            .map(|(_, b)| b)
            .chain(method_only_generics.iter().map(|(_, b)| b))
            .collect();
        if all.is_empty() {
            quote! {}
        } else {
            quote! { < #( #all ),* > }
        }
    };

    // Single-element tuples need a trailing comma.
    let op_args_tuple_ty = single_or_tuple(&arg_types);
    // `op_args_tuple_init` = construction (slices wrapped via to_input).
    // `op_args_tuple_pat` = destructure pattern at enqueue (plain names).
    let op_args_tuple_init = single_or_tuple(&op_field_init);
    let op_args_tuple_pat = single_or_tuple(&host_names);
    let op_launch_args_tuple = single_or_tuple(&op_arg_pass);

    // Output type / expression — bare for a single slice, tuple for
    // many, `()` for none. Same convention on both terminals
    // (`wait`/`submit`) and the `DeviceOperation::Output`.
    let (output_ty, output_expr) = match output_names.len() {
        0 => (quote! { () }, quote! { () }),
        1 => {
            let n = &output_names[0];
            let t = &output_types[0];
            (quote! { #t }, quote! { #n })
        }
        _ => (
            quote! { ( #(#output_types),* ) },
            quote! { ( #(#output_names),* ) },
        ),
    };

    let kernels_path = &args.kernels;

    // Hidden submodule per kernel: holds the Op struct + impls. The
    // module name keeps the legacy `_op` suffix purely to namespace
    // emissions; users only see `kernels.<name>(...)` and the Op type
    // is doc-hidden.
    let op_mod_ident = quote::format_ident!("__claspr_{}_op", name);
    let kernel_name_lit = name.to_string();

    // Emit ONE method on `Kernels`, named after the kernel. It returns
    // a per-kernel `Op` struct that:
    //
    //   - implements Tier 1 terminals (`.wait(launcher) -> Output`,
    //     `.submit(launcher) -> (Output, Event)`)
    //   - implements builder modifiers (`.after(event)`,
    //     `.after_all(events)`, `.profiled(cb)`)
    //   - implements `DeviceOperation` (Tier 2 chain use)
    //
    // The method calls `kernels.kernel("<name>")` to mint a fresh
    // `cl_kernel` handle owned by the resulting Op. Per-launch
    // `clCreateKernel` keeps `clSetKernelArg` state private to each Op
    // — no possible race even when two chains target the same kernel.
    // Panics on the (extremely rare) `clCreateKernel` OOM because
    // `Kernels::load` already validated every entry point.
    //
    // Because the Op owns its `Kernel` and no longer borrows `&Kernels`,
    // it has **no lifetime parameter** — moving Ops into `tokio::spawn`
    // / threads / `'static` futures is straightforward.
    //
    // Tier 2 (`DeviceOperation`) is provided by a blanket
    // `impl<O: claspr::KernelOp + 'static> DeviceOperation for O`
    // in `claspr-async` — so the macro emits only the inherent
    // terminals + a `KernelOp` impl, never mentions `claspr-async`,
    // and Tier 1-only consumers can leave `claspr-async` out of
    // their dep graph entirely.
    //
    // `#[allow(clippy::too_many_arguments)]` — the wrapper's arg count
    // is determined by the kernel's declared signature, not user
    // choice, so a per-call `#[allow]` would burden every user.
    Ok(quote! {
        impl #kernels_path {
            #[allow(clippy::too_many_arguments)]
            #vis fn #name #method_gen_decl (
                &self,
                grid: impl ::claspr::IntoLaunchSpec,
                #(#method_params),*
            ) -> #op_mod_ident::Op #gen_use {
                #op_mod_ident::Op {
                    kernel: self.kernel(#kernel_name_lit),
                    spec: ::claspr::IntoLaunchSpec::into_launch_spec(grid),
                    args: #op_args_tuple_init,
                    deps: ::std::vec::Vec::new(),
                    profile_cb: ::core::option::Option::None,
                    ctx: ::core::clone::Clone::clone(&self.__claspr_ctx),
                }
            }
        }

        #[doc(hidden)]
        #[allow(non_snake_case, non_camel_case_types, unused_imports)]
        pub mod #op_mod_ident {
            use super::*;

            pub struct Op #gen_decl {
                /// Per-launch `cl_kernel` minted by `clCreateKernel`.
                /// Owned and never aliased, so `clSetKernelArg` on it
                /// can't race with any other launch.
                pub kernel: ::claspr::Kernel,
                pub spec: ::claspr::LaunchSpec,
                pub args: #op_args_tuple_ty,
                /// Caller-added wait-list events. Owned so the Op is
                /// `Send` across executor threads — raw `cl_event`
                /// handles aren't, and a borrowed `&Event` can't outlive
                /// its source binding once the Op is moved.
                pub deps: ::std::vec::Vec<::claspr::Event>,
                pub profile_cb: ::core::option::Option<::claspr::ProfileCb>,
                /// Carried `Context` so the no-arg `.wait()` /
                /// `.submit()` terminals can submit on its default
                /// in-order queue without taking an explicit
                /// launcher. Cloned from `Kernels`'s context at
                /// launcher-method emission time.
                pub ctx: ::claspr::Context,
            }

            // Op is `Send` automatically — every field is Send. No
            // unsafe impl, no lifetime, no `&Kernels` borrow.

            impl #gen_decl Op #gen_use {
                /// Add a cross-queue dependency. Takes the event by
                /// value because the Op may be moved into an executor
                /// thread; a borrowed `&Event` could outlive the
                /// caller's binding. Chainable.
                pub fn after(mut self, event: ::claspr::Event) -> Self {
                    self.deps.push(event);
                    self
                }

                /// Add multiple wait-list events at once. Chainable.
                pub fn after_all<I>(mut self, events: I) -> Self
                where
                    I: ::core::iter::IntoIterator<Item = ::claspr::Event>,
                {
                    self.deps.extend(events);
                    self
                }

                /// Register a completion callback for profiling info.
                /// Chainable.
                pub fn profiled<F>(mut self, cb: F) -> Self
                where
                    F: ::core::ops::FnOnce(::claspr::Result<::claspr::ProfilingInfo>)
                        + ::core::marker::Send
                        + 'static,
                {
                    self.profile_cb = ::core::option::Option::Some(
                        ::std::boxed::Box::new(cb),
                    );
                    self
                }

                /// Tier 1 non-blocking terminal — enqueue on the
                /// carried `Kernels`' context default queue and
                /// return `(Output, Event)`.
                pub fn submit(
                    self,
                ) -> ::claspr::Result<(#output_ty, ::claspr::Event)> {
                    let ctx = ::core::clone::Clone::clone(&self.ctx);
                    self.submit_on(&ctx)
                }

                /// Tier 1 non-blocking terminal with an explicit
                /// launcher — enqueue on `launcher`'s queue and
                /// return `(Output, Event)` so the caller can keep
                /// using the buffers and chain via `.after(event)`.
                ///
                /// Panics if any caller-added dep event (from
                /// `.after()` / `.after_all()`) was produced on a
                /// different `Context` than `launcher`'s queue.
                pub fn submit_on<L>(
                    self,
                    launcher: &L,
                ) -> ::claspr::Result<(#output_ty, ::claspr::Event)>
                where
                    L: ::claspr::Launcher,
                {
                    <Self as ::claspr::KernelOp>::enqueue_into(self, launcher, &[])
                }

                /// Tier 1 blocking terminal — submit on the carried
                /// `Kernels`' context default queue and wait on the
                /// completion event. Returns the slice arg(s) so the
                /// caller can keep using them.
                pub fn wait(self) -> ::claspr::Result<#output_ty> {
                    let ctx = ::core::clone::Clone::clone(&self.ctx);
                    self.wait_on(&ctx)
                }

                /// Tier 1 blocking terminal with an explicit launcher.
                pub fn wait_on<L>(self, launcher: &L) -> ::claspr::Result<#output_ty>
                where
                    L: ::claspr::Launcher,
                {
                    let (out, event) = self.submit_on(launcher)?;
                    event.wait()?;
                    ::core::result::Result::Ok(out)
                }
            }

            // Sealed-trait witness, paired with the `KernelOp` impl
            // below. `__seal::Sealed` is `#[doc(hidden)]` in claspr;
            // its only public emission site is right here.
            impl #gen_decl ::claspr::__seal::Sealed for Op #gen_use {}

            // Single enqueue body shared by `.submit` (Tier 1) and by
            // `claspr-async`'s blanket `DeviceOperation` impl (Tier 2).
            // `extra_deps` is the chain's upstream wait-list when called
            // from the Tier 2 blanket impl; an empty slice when called
            // from `.submit`.
            impl #gen_decl ::claspr::KernelOp for Op #gen_use {
                type Output = #output_ty;

                fn enqueue_into<L>(
                    self,
                    launcher: &L,
                    extra_deps: &[::claspr::cl_event],
                ) -> ::claspr::Result<(Self::Output, ::claspr::Event)>
                where
                    L: ::claspr::Launcher,
                {
                    let Op { kernel, spec, args, deps, profile_cb, ctx: _ } = self;
                    // Validate cross-context match for every caller-added
                    // dep. The launcher's context is known here; the
                    // check is two CL info queries + a pointer compare
                    // per dep (cheap), and surfaces mismatches as a
                    // clear panic instead of a cryptic CL_INVALID_CONTEXT
                    // at enqueue time. Chain-supplied `extra_deps` come
                    // from the same ExecutionContext upstream, so they
                    // don't need re-checking.
                    for ev in &deps {
                        ::claspr::assert_same_context(
                            ev,
                            launcher.cl_queue(),
                            concat!("kernel `", stringify!(#name), "` KernelOp::enqueue_into"),
                        );
                    }
                    // Hand LaunchOp raw cl_event handles; `deps` (owned
                    // events) stays alive until after the enqueue returns,
                    // at which point OpenCL has retained them internally
                    // for the wait list.
                    let mut raw_deps: ::std::vec::Vec<::claspr::cl_event> =
                        ::std::vec::Vec::with_capacity(deps.len() + extra_deps.len());
                    raw_deps.extend(deps.iter().map(|e| e.get()));
                    raw_deps.extend_from_slice(extra_deps);
                    let #op_args_tuple_pat = args;
                    // Resolve each slice `Input<__D>` → concrete buffer (Tier-1
                    // path; a pipe here errors). Scalars need no resolution.
                    #(#input_resolve)*
                    let event = ::claspr::LaunchOp::new(
                        launcher,
                        &kernel,
                        spec,
                        #op_launch_args_tuple,
                    )
                    .with_state(raw_deps, profile_cb)
                    .submit()?;
                    ::core::mem::drop(deps);
                    ::core::mem::drop(kernel);
                    ::core::result::Result::Ok((#output_expr, event))
                }
            }
        }
    })
}

/// Tuples with a single element need a trailing comma in Rust. Helper
/// to emit either `(only,)` or `(a, b, c)` based on element count.
/// Returns `()` for an empty list.
fn single_or_tuple(elems: &[TokenStream2]) -> TokenStream2 {
    match elems.len() {
        0 => quote! { () },
        1 => {
            let only = &elems[0];
            quote! { ( #only, ) }
        }
        _ => quote! { ( #(#elems),* ) },
    }
}

enum ParamRole {
    /// Drop: SPIR-V builtin filled in by the runtime.
    Builtin,
    /// Slice param (`#[spirv(cross_workgroup)] &mut [T]` or `&[T]`).
    /// Becomes a generic type parameter `D: KernelSliceReadArg<T>`
    /// (for `&[T]`) or `D: KernelSliceReadWriteArg<T>` (for `&mut [T]`)
    /// on the emitted method + Op, so any of `DeviceSlice<T, M>` /
    /// `MappedSlice<T>` / `USMSlice<T>` can flow through — subject to
    /// the marker's `KernelReadable` / `KernelWritable` constraints.
    Slice {
        name: TokenStream2,
        /// The `T` from `&[T]` / `&mut [T]` — used to constrain the generic.
        elem: TokenStream2,
        /// `true` when the kernel param is `&mut [T]` (emits the
        /// stricter `KernelSliceReadWriteArg<T>` bound); `false` for
        /// `&[T]` (emits `KernelSliceReadArg<T>`).
        mutable: bool,
    },
    /// Image param (`&Image!(...)` / `&mut Image!(...)`). Becomes a
    /// pair of generic type parameters on the emitted method:
    ///   - `__claspr_F{n}: format::Format<SampledFamily = K>`
    ///   - `__claspr_I{n}: KernelImage<dim>D<Access>Arg<K>`
    ///
    /// `K` is the sampled-type family (`Uint`/`Sint`/`Float`)
    /// derived from the kernel's `type=` keyword. `<Access>` is
    /// `Read`/`Write`/`ReadWrite` derived from `&`/`&mut` plus the
    /// optional `#[spirv(image_access = "...")]` override. `<dim>`
    /// is `1D`/`2D`/`3D` from the `Image!(<dim>, ...)` token.
    Image {
        name: TokenStream2,
        /// Dim segment as it appears in the host trait name —
        /// `"1D"` / `"2D"` / `"3D"` / `"Buffer"`. Spliced via
        /// `format_ident!` into
        /// `KernelImage<dim><Access>Arg<family>` (note: the literal
        /// `D` is part of the dim segment, not the trait stem, so
        /// `Buffer` works as a drop-in too).
        dim: &'static str,
        /// Sampled-type-family marker path:
        /// `::claspr::image::format::Uint` etc.
        family: TokenStream2,
        /// Trait family name segment: `Read`, `Write`, or
        /// `ReadWrite`. Spliced via `format_ident!` into
        /// `KernelImage<dim>D<segment>Arg<family>`.
        access_segment: &'static str,
    },
    /// Scalar param (no spirv attribute). Passed by value, doesn't
    /// thread through Output.
    Scalar {
        name: TokenStream2,
        ty: TokenStream2,
    },
}

fn classify_param(pt: &PatType) -> syn::Result<ParamRole> {
    let attr = find_spirv_attr(&pt.attrs);
    let kind = attr.as_ref().map(spirv_attr_kind);

    // Anything tagged with a SPIR-V builtin name (global_invocation_id,
    // workgroup_id, local_invocation_id, …) is a runtime-filled input,
    // not a host kernel argument. The complete list lives in
    // `spirv-std::spirv` — rather than enumerate every keyword, we
    // treat everything except `cross_workgroup` as a builtin. This
    // matches the rust-gpu convention where `cross_workgroup` is the
    // *only* attribute that names a host-supplied buffer.
    if matches!(kind, Some(SpirvKind::Builtin)) {
        return Ok(ParamRole::Builtin);
    }

    let pname = match &*pt.pat {
        Pat::Ident(pi) => {
            let id = &pi.ident;
            quote! { #id }
        }
        other => {
            return Err(syn::Error::new(
                other.span(),
                "claspr::kernel parameter pattern must be a plain identifier",
            ));
        }
    };

    if matches!(kind, Some(SpirvKind::CrossWorkgroup)) {
        let (elem, mutable) = slice_element_ty(&pt.ty)?;
        return Ok(ParamRole::Slice {
            name: pname,
            elem,
            mutable,
        });
    }
    if let Some(info) = classify_image_param(pt)? {
        return Ok(ParamRole::Image {
            name: pname,
            dim: info.dim,
            family: info.family,
            access_segment: info.access_segment,
        });
    }
    let t = &pt.ty;
    Ok(ParamRole::Scalar {
        name: pname,
        ty: quote! { #t },
    })
}

/// Pull `(element type, is-mutable)` out of `&[T]` / `&mut [T]`.
/// The mutability bit drives the choice between
/// `KernelSliceReadArg<T>` (`&[T]`) and `KernelSliceReadWriteArg<T>`
/// (`&mut [T]`) bounds on the emitted host method.
fn slice_element_ty(ty: &Type) -> syn::Result<(TokenStream2, bool)> {
    let Type::Reference(TypeReference {
        elem, mutability, ..
    }) = ty
    else {
        return Err(syn::Error::new(
            ty.span(),
            "expected a reference type (`&[T]` or `&mut [T]`) for a #[spirv(cross_workgroup)] \
             parameter; other shapes are not yet supported by claspr::kernel",
        ));
    };
    let Type::Slice(TypeSlice { elem: inner, .. }) = &**elem else {
        return Err(syn::Error::new(
            elem.span(),
            "expected a slice type `[T]` after the reference; other shapes are not yet supported \
             by claspr::kernel",
        ));
    };
    Ok((quote! { #inner }, mutability.is_some()))
}

fn find_spirv_attr(attrs: &[Attribute]) -> Option<Attribute> {
    attrs.iter().find(|a| a.path().is_ident("spirv")).cloned()
}

enum SpirvKind {
    /// `#[spirv(cross_workgroup)]` — host-supplied buffer; translate type.
    CrossWorkgroup,
    /// `#[spirv(image_access = "...")]` — host-supplied image with
    /// explicit access-qualifier override on the kernel side. Param
    /// stays in the host signature; the macro inspects this attr (in
    /// addition to the Image! tokens) when picking the host-side
    /// trait-bound variant.
    ImageAccess,
    /// Anything else (`#[spirv(global_invocation_id)]`, `workgroup`, …)
    /// — drop from host signature.
    Builtin,
}

fn spirv_attr_kind(attr: &Attribute) -> SpirvKind {
    // We want to know whether the inner meta starts with `cross_workgroup`,
    // `image_access`, or something else. Use the parse_args-as-token-stream
    // path so we don't have to enumerate every spirv attribute syn might
    // know about.
    let tokens = attr.meta.require_list().ok().map(|l| l.tokens.clone());
    let Some(tokens) = tokens else {
        return SpirvKind::Builtin;
    };
    let first_ident = tokens
        .into_iter()
        .find_map(|tt| match tt {
            proc_macro2::TokenTree::Ident(i) => Some(i.to_string()),
            _ => None,
        })
        .unwrap_or_default();
    match first_ident.as_str() {
        "cross_workgroup" => SpirvKind::CrossWorkgroup,
        "image_access" => SpirvKind::ImageAccess,
        _ => SpirvKind::Builtin,
    }
}

/// Parsed `Image!(...)` parameter info: dim + sampled-type family +
/// access-trait segment, threaded through to the macro emission to
/// drive per-image generic decls + the trait bound on the wrapper
/// method.
struct ImageInfo {
    /// Dim segment as it appears in the host trait + wrapper name:
    /// `"1D"`/`"2D"`/`"3D"` from `Image!(1D|2D|3D, ...)`, `"Buffer"`
    /// from `Image!(buffer, ...)`. Spliced into
    /// `KernelImage<dim><Access>Arg`.
    dim: &'static str,
    /// Path to the sampled-type-family marker ZST —
    /// `::claspr::image::format::{Uint, Sint, Float}` — derived from
    /// the kernel's `type=` keyword.
    family: TokenStream2,
    /// One of `Read` / `Write` / `ReadWrite` — gets spliced via
    /// `format_ident!` into
    /// `::claspr::KernelImage<dim>D<segment>Arg<family>` to form the
    /// trait bound on the wrapper's image generic.
    access_segment: &'static str,
}

/// Recognise `&Image!(...)` / `&mut Image!(...)` and translate the
/// macro tokens + param attributes into the (dim, family,
/// access_segment) tuple the emission needs.
///
/// Access derivation (independent of `Image!` tokens — looks at
/// `&`/`&mut` + the optional `#[spirv(image_access = "...")]`
/// param attribute claspr-macros recognised from rust-gpu's new
/// kernel-side keyword):
///   - `&Image!(...)` → `Read` (kernel declared `ReadOnly`)
///   - `&mut Image!(...)` → `ReadWrite` by default; `Write` if
///     `#[spirv(image_access = "write_only")]` overrides;
///     `ReadWrite` if `read_write` (redundant but accepted).
///   - `#[spirv(image_access = "read_only")]` on `&` is redundant
///     but accepted; on `&mut` is a coherence error.
///   - `read_write`/`write_only` on `&` is a coherence error.
///
/// Coherence errors mirror what rust-gpu enforces on the kernel
/// side — both sides should reject the same shapes.
///
/// Sampled-family derivation from the `type=` keyword inside
/// `Image!(...)`:
///   - `type=u32`/`u8`/`u16`/`u64` → `Uint`
///   - `type=i32`/`i8`/`i16`/`i64` → `Sint`
///   - `type=f32`/`f64` → `Float`
///   - (no `type=`) → `Uint` default (matches rust-gpu's behaviour
///     when neither `type=` nor `format=` is set; the user should
///     really write `type=u32` explicitly, but we don't fail here)
///
/// Dim derivation from the leading `Image!(<dim>, ...)` ident:
///   - `1D` → 1; `2D` → 2; `3D` → 3
///   - other shapes (`cube`, `rect`, `buffer`, `subpass`) → error
///     pointing at the unsupported dim (claspr doesn't currently
///     wrap these — extension worth doing when first needed)
///
/// Returns `Ok(None)` if `pt.ty` doesn't look like an `Image!(...)`
/// ref. `Err` if it does but something's incoherent.
fn classify_image_param(pt: &PatType) -> syn::Result<Option<ImageInfo>> {
    let Type::Reference(TypeReference {
        elem, mutability, ..
    }) = &*pt.ty
    else {
        return Ok(None);
    };
    let Type::Macro(TypeMacro { mac }) = &**elem else {
        return Ok(None);
    };
    if !mac.path.is_ident("Image") {
        return Ok(None);
    }
    let mutable = mutability.is_some();
    let span = pt.ty.span();

    let (dim_tok, type_tok, arrayed) = parse_image_tokens(mac.tokens.clone());

    let dim = match (dim_tok.as_deref(), arrayed) {
        (Some("1D"), false) => "1D",
        (Some("2D"), false) => "2D",
        (Some("3D"), false) => "3D",
        // `Image!(1D, arrayed=true, ...)` / `Image!(2D, arrayed=true, ...)`
        // → `Image1DArray<A, F>` / `Image2DArray<A, F>` host wrapper
        // + the matching `KernelImage<dim>Array*Arg` trait family.
        // Kernel-side coord is one component wider than the
        // non-arrayed form (IVec2 for 1D-array, IVec3 for 2D-array).
        (Some("1D"), true) => "1DArray",
        (Some("2D"), true) => "2DArray",
        (Some("3D"), true) => {
            // 3D-arrayed isn't a thing in SPIR-V or OpenCL —
            // there's no `image3d_array_t`. Catch it explicitly so
            // the error points at the user's mistake instead of
            // failing later with a missing-trait diagnostic.
            return Err(syn::Error::new(
                span,
                "claspr::kernel: `Image!(3D, arrayed=true, ...)` is not legal — \
                 3D image arrays don't exist in OpenCL / SPIR-V",
            ));
        }
        // rust-gpu's `Image!(buffer, ...)` (lowercase ident,
        // matching spirv-std-macros) → `Image1DBuffer` host wrapper
        // + `KernelImageBuffer*Arg` trait family. Backed by a
        // `cl_mem` buffer object, so it can either own its storage
        // (alloc) or view an existing `DeviceSlice<T>`.
        (Some("buffer"), false) => "Buffer",
        (Some("buffer"), true) => {
            return Err(syn::Error::new(
                span,
                "claspr::kernel: `Image!(buffer, arrayed=true, ...)` is not legal — \
                 image buffers are inherently 1D and don't support arraying",
            ));
        }
        (Some(other), _) => {
            return Err(syn::Error::new(
                span,
                format!(
                    "claspr::kernel: unsupported Image! dimensionality `{other}`. \
                     Supported: `1D`, `2D`, `3D`, `buffer` (cube/rect/subpass \
                     have no claspr host counterpart yet)"
                ),
            ));
        }
        (None, _) => {
            return Err(syn::Error::new(
                span,
                "claspr::kernel: Image! parameter missing dimensionality — expected `Image!(1D, ...)`, \
                 `Image!(2D, ...)`, `Image!(3D, ...)`, or `Image!(buffer, ...)` as the first token",
            ));
        }
    };

    let family = match type_tok.as_deref() {
        Some("f32") | Some("f64") => quote! { ::claspr::image::format::Float },
        Some("i32") | Some("i64") | Some("i8") | Some("i16") => {
            quote! { ::claspr::image::format::Sint }
        }
        // `u32`/`u8`/`u16`/`u64` + the no-`type=` catch-all map to
        // `Uint`, matching the existing default that pairs with
        // rust-gpu's `Image!(...)` when no `type=` is given.
        _ => quote! { ::claspr::image::format::Uint },
    };

    // Access derivation. The override (if present) wins over the
    // mutability-based default; mismatch is a coherence error.
    let explicit_access = read_image_access_attr(&pt.attrs);
    let access_segment_str = match (mutable, explicit_access.as_deref()) {
        // No override — derive from mutability.
        (false, None) => "Read",
        (true, None) => "ReadWrite",
        // Explicit override aligned with mutability.
        (false, Some("read_only")) => "Read",
        (true, Some("read_write")) => "ReadWrite",
        (true, Some("write_only")) => "Write",
        // Coherence violations.
        (false, Some("write_only")) | (false, Some("read_write")) => {
            return Err(syn::Error::new(
                span,
                "claspr::kernel: `#[spirv(image_access = \"write_only\"|\"read_write\")]` requires \
                 a `&mut Image!` parameter, but this is `&Image!`",
            ));
        }
        (true, Some("read_only")) => {
            return Err(syn::Error::new(
                span,
                "claspr::kernel: `#[spirv(image_access = \"read_only\")]` requires a `&Image!` \
                 parameter, but this is `&mut Image!`",
            ));
        }
        (_, Some(other)) => {
            return Err(syn::Error::new(
                span,
                format!(
                    "claspr::kernel: unknown image_access `{other}` — expected `read_only`, \
                     `write_only`, or `read_write`"
                ),
            ));
        }
    };
    Ok(Some(ImageInfo {
        dim,
        family,
        access_segment: access_segment_str,
    }))
}

/// Find a `#[spirv(image_access = "<value>")]` attribute on the
/// param and return the string value if present. Mirrors rust-gpu's
/// kernel-side recognition of the same attribute — see
/// `crates/rustc_codegen_spirv/src/attr.rs::parse_image_access_attr`
/// on the rust-gpu side; both must agree on the recognised set
/// (`read_only` / `write_only` / `read_write`).
fn read_image_access_attr(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("spirv") {
            continue;
        }
        let Ok(meta) = attr.meta.require_list() else {
            continue;
        };
        let tts: Vec<proc_macro2::TokenTree> = meta.tokens.clone().into_iter().collect();
        // Look for `image_access = "<value>"` — five-token sequence:
        // Ident("image_access") Punct('=') Literal("...")
        // (with optional commas before/after — we just scan for the
        // ident, then advance two slots looking for the literal).
        for i in 0..tts.len() {
            let Some(proc_macro2::TokenTree::Ident(key)) = tts.get(i) else {
                continue;
            };
            if *key != "image_access" {
                continue;
            }
            let (
                Some(proc_macro2::TokenTree::Punct(eq)),
                Some(proc_macro2::TokenTree::Literal(lit)),
            ) = (tts.get(i + 1), tts.get(i + 2))
            else {
                continue;
            };
            if eq.as_char() != '=' {
                continue;
            }
            // Literal::to_string includes the surrounding quotes —
            // strip them. We accept double-quoted strings only.
            let s = lit.to_string();
            if let Some(inner) = s.strip_prefix('"').and_then(|t| t.strip_suffix('"')) {
                return Some(inner.to_string());
            }
        }
    }
    None
}

/// Scan an `Image!(...)` token list for:
/// - the leading dim ident (`1D`/`2D`/`3D`/`cube`/etc.),
/// - the `type=<ident>` value (drives the sampled-type family),
/// - the `arrayed=true|false` flag (drives the `*Array` host
///   wrapper selection).
///
/// Other keywords (`sampled=`, `multisampled=`, `depth=`,
/// `format=`, `components=`) are recognised by rust-gpu's
/// `Image!` macro but don't influence the claspr host-wrapper
/// signature — `format=` is Shader-only and unreachable from
/// claspr's OpenCL Kernel target, the rest are runtime/usage
/// hints that the host `Image<dim>D<A, F>` doesn't need to
/// encode.
///
/// Returns `(dim_ident, type_value, arrayed)`. Dim recognition
/// handles both the `LitInt`-suffix form (`1D` is `1` with
/// suffix `D`) and the bare `Ident` form (`cube`, `rect`,
/// `buffer`, `subpass`). `arrayed` defaults to false if absent.
fn parse_image_tokens(tokens: TokenStream2) -> (Option<String>, Option<String>, bool) {
    let mut dim: Option<String> = None;
    let mut type_: Option<String> = None;
    let mut arrayed = false;
    let tts: Vec<proc_macro2::TokenTree> = tokens.into_iter().collect();
    let mut i = 0;
    while i < tts.len() {
        // First-token-only: dim ident. Subsequent positions only
        // accept keyword=value triples.
        if dim.is_none() {
            match &tts[i] {
                proc_macro2::TokenTree::Literal(lit) => {
                    // rust-gpu's parser accepts `1D`/`2D`/`3D` as
                    // `LitInt` with a suffix; reconstruct the form.
                    let s = lit.to_string();
                    if matches!(s.as_str(), "1D" | "2D" | "3D") {
                        dim = Some(s);
                        i += 1;
                        // skip trailing comma if any
                        if matches!(
                            tts.get(i),
                            Some(proc_macro2::TokenTree::Punct(p)) if p.as_char() == ','
                        ) {
                            i += 1;
                        }
                        continue;
                    }
                }
                proc_macro2::TokenTree::Ident(id) => {
                    let s = id.to_string();
                    if matches!(s.as_str(), "cube" | "rect" | "buffer" | "subpass") {
                        dim = Some(s);
                        i += 1;
                        if matches!(
                            tts.get(i),
                            Some(proc_macro2::TokenTree::Punct(p)) if p.as_char() == ','
                        ) {
                            i += 1;
                        }
                        continue;
                    }
                }
                _ => {}
            }
        }
        // Look for `<ident> = <ident>` triples (Image! `key=value`
        // form). Standalone idents elsewhere (e.g. `sampled` shorthand
        // for `sampled=true`) get skipped without comment.
        if let (
            Some(proc_macro2::TokenTree::Ident(key)),
            Some(proc_macro2::TokenTree::Punct(eq)),
            Some(proc_macro2::TokenTree::Ident(val)),
        ) = (tts.get(i), tts.get(i + 1), tts.get(i + 2))
            && eq.as_char() == '='
        {
            if *key == "type" {
                type_ = Some(val.to_string());
                i += 3;
                continue;
            }
            if *key == "arrayed" {
                // `arrayed=true` or `arrayed=false`. Anything else
                // is treated as false (mirroring how rust-gpu's
                // macro parses bool literals).
                arrayed = *val == "true";
                i += 3;
                continue;
            }
        }
        i += 1;
    }
    (dim, type_, arrayed)
}
