//! Proc-macro frontend for [claspr] — write a kernel function once
//! with kernel-style attributes and signature, get a host-side launch
//! wrapper for free.
//!
//! ## Generated shape
//!
//! For each `#[claspr::kernel] fn foo(...)`, the macro emits a single
//! method `Kernels::foo(grid, slice_by_value, scalar)` that returns a
//! per-kernel `Op` struct. The Op works in two modes:
//!
//! - **Tier 1 (sync, explicit launcher):** `.wait(launcher) -> Output`
//!   or `.submit(launcher) -> (Output, Event)`. Modifiers: `.after(ev)`,
//!   `.after_all(events)`, `.profiled(cb)`.
//! - **Tier 2 (async chain):** the Op implements `DeviceOperation`,
//!   so it composes into `.and_then` / `bundle!` / `fan_out` chains.
//!
//! `Output` is the slice arg(s) the kernel touches — bare for one
//! slice, tuple for many, `()` for none. Scalars are dropped from
//! `Output`. The same single method serves both contexts.
//!
//! ## Example
//!
//! ```ignore
//! mod kernels {
//!     include!(concat!(env!("OUT_DIR"), "/collatz_kernels.rs"));
//! }
//!
//! // Stub mirrors the kernel signature exactly. Body is discarded
//! // by the proc-macro; leave it empty or copy-paste the real kernel
//! // body for documentation / future single-source extraction.
//! #[claspr::kernel]
//! fn collatz_kernel(
//!     #[spirv(global_invocation_id)] _id: USizeVec3,
//!     #[spirv(cross_workgroup)] data: &mut [u32],
//! ) {}
//!
//! fn main() -> claspr::Result<()> {
//!     let ctx = claspr::Context::any()?;
//!     let kernels = kernels::Kernels::load(&ctx)?;
//!     let mut data: Vec<u32> = (1..=1024).collect();
//!     let mut buf = claspr::DeviceSlice::alloc(&ctx, data.len())?;
//!     buf.write(&ctx, &data).wait()?;
//!     // Tier 1: slices move in, come back out of `.wait()`.
//!     let buf = kernels.collatz_kernel([data.len()], buf).wait(&ctx)?;
//!     buf.read(&ctx, &mut data).wait()?;
//!     Ok(())
//! }
//! ```
//!
//! ## In an async chain
//!
//! ```ignore
//! use claspr_async::{DeviceOperation, download, upload};
//!
//! let result: Vec<u32> = upload(initial_data)
//!     .and_then(|buf| kernels.fill_u32([N], buf, 5))
//!     .and_then(|buf| kernels.scale_u32([N], buf, 3))
//!     .and_then(download)
//!     .sync(&ctx)?;
//! ```
//!
//! [claspr]: https://github.com/bricevideau-ai/claspr

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{
    Attribute, FnArg, ItemFn, Pat, PatType, Path, Type, TypeMacro, TypeReference, TypeSlice,
    parse_macro_input, spanned::Spanned,
};

/// Mark a function as a claspr kernel — generates a host-side launch
/// wrapper.
///
/// See the crate-level docs for the rough shape; behaviour follows
/// these rules when walking the stub's parameters:
///
/// - A parameter with a `#[spirv(<builtin>)]` attribute (anything except
///   `cross_workgroup` or no attribute) is **dropped** — these are
///   SPIR-V built-in inputs filled in by the OpenCL runtime, not
///   host-side arguments.
/// - A parameter `#[spirv(cross_workgroup)] name: &mut [T]` or `&[T]`
///   is **translated** to `name: ::claspr::DeviceSlice<T>` (owned by
///   the emitted Op; flows through `Output`).
/// - A parameter `&Image!(...)` is translated to `::claspr::Image2D<A, F>`
///   (also owned and threaded through `Output`).
/// - Any other parameter is passed through verbatim — used for scalar
///   `T` arguments via the `claspr::scalar_arg!`-emitted `KernelArg`
///   impl. Scalars do *not* flow through `Output`.
#[proc_macro_attribute]
pub fn kernel(attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let attr_args = match parse_attr_args(attr) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error().into(),
    };
    match expand_kernel(&func, &attr_args) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Mark a function **or a module** as device-side code — included in
/// the kernel sub-crate generated by `claspr_build::compile_from_host`,
/// otherwise a no-op on the host beyond suppressing dead-code warnings.
///
/// On a **function**, signals to the build script that this helper
/// should be copied into the kernel crate alongside the
/// `#[claspr::kernel]`-marked entry points that call it. The macro
/// adds `#[allow(dead_code)]` so the host doesn't warn when only the
/// kernel-side compilation actually uses the function.
///
/// On a **module**, the macro does *two* things:
///
/// 1. Lifts the whole module body into the generated kernel crate at
///    build time — every `use`, `const`, `static`, helper `fn`, type
///    def, even nested modules.
/// 2. Appends two items **inside** the module body for the host build:
///    `include!(concat!(env!("OUT_DIR"), "/kernels.rs"));` (which
///    pulls in the build-script-generated `Kernels` struct and
///    `Kernels::load`) and a `pub fn kernels(ctx: &Context) -> Result<Kernels>`
///    convenience wrapper. Calling code reads `gpu::kernels(&ctx)?`,
///    and `#[claspr::kernel]` defaults to targeting `Kernels` —
///    relative to where the macro is invoked, which is inside the
///    same module.
///
/// Because each `#[claspr::device]` module owns its own `Kernels`
/// struct and `kernels()` function, multiple device modules can sit
/// in the same file without colliding (they live in different
/// module-namespaces).
///
/// The build script must write to `OUT_DIR/<modname>.rs` for step 2
/// to find the generated module — `claspr_build::compile_from_host(...).write()`
/// derives the filename from each `#[claspr::device] mod <name>` it
/// discovers, so the coupling matches automatically.
///
/// ```ignore
/// #[claspr::device]
/// mod gpu {
///     use spirv_std::cl::Float3;
///     pub const RADIUS: f32 = 0.9;
///
///     pub fn helper(p: Float3) -> f32 { /* shared host+device helper */ }
///
///     #[claspr::kernel] // defaults to `kernels = Kernels` (in scope here)
///     pub fn raymarch(/* ... */) { /* uses RADIUS, helper, etc. */ }
/// }
///
/// // host code:
/// let kernels = gpu::kernels(&ctx)?;
/// kernels.raymarch(&ctx, /* ... */)?;
/// ```
///
/// Items at the same scope as the device module that aren't tagged
/// `#[claspr::kernel]` or `#[claspr::device]` are host-only —
/// `claspr-build` skips them when generating the kernel crate, so
/// things like `use claspr::*` and `fn main()` work normally.
#[proc_macro_attribute]
pub fn device(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let item_ts: TokenStream2 = item.into();
    // Parse to decide between the fn form and the mod form.
    let parsed: syn::Result<syn::Item> = syn::parse2(item_ts.clone());
    if let Ok(syn::Item::Mod(mut item_mod)) = parsed {
        if let Some((_, items)) = &mut item_mod.content {
            // Append the include and the convenience `kernels()` fn
            // *inside* the user's module body. Filename matches the
            // module name so multiple `#[claspr::device]` modules in
            // the same file don't share output (build script writes
            // `OUT_DIR/<modname>.rs` per device module). Order
            // doesn't matter for type/method resolution within a
            // module — the impl blocks emitted by `#[claspr::kernel]`
            // (also inside this module) find `Kernels` regardless of
            // where the include lands.
            let mod_filename = format!("/{}.rs", item_mod.ident);
            let include_item: syn::Item = syn::parse_quote! {
                include!(concat!(env!("OUT_DIR"), #mod_filename));
            };
            let kernels_fn: syn::Item = syn::parse_quote! {
                /// Build the program from the embedded SPIR-V and look up every entry point.
                pub fn kernels(ctx: &::claspr::Context) -> ::claspr::Result<Kernels> {
                    Kernels::load(ctx)
                }
            };
            items.push(include_item);
            items.push(kernels_fn);
        }
        let body = quote! { #item_mod };
        return quote! {
            #[allow(dead_code, unused_imports)]
            #body
        }
        .into();
    }
    // Function form (or anything else): same `#[allow(...)]` wrap as
    // before. `unused_imports` is in there because a device module's
    // `use` statements often look unused on the host (the kernel
    // body that uses them is discarded by `#[claspr::kernel]`).
    quote! {
        #[allow(dead_code, unused_imports)]
        #item_ts
    }
    .into()
}

struct AttrArgs {
    /// Path to the build-script-generated `Kernels` struct that this
    /// kernel's typed launch method will be added to.
    kernels: Path,
}

fn parse_attr_args(attr: TokenStream) -> syn::Result<AttrArgs> {
    let mut kernels: Option<Path> = None;
    let parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("kernels") {
            kernels = Some(meta.value()?.parse::<Path>()?);
            Ok(())
        } else {
            Err(meta.error(
                "unsupported claspr::kernel argument; expected `kernels = path::to::Kernels`",
            ))
        }
    });
    syn::parse::Parser::parse(parser, attr)?;
    // Default to `Kernels` (relative path) — `#[claspr::device]` on
    // a module includes the generated `Kernels` struct at the end of
    // the module body, so a `#[claspr::kernel]` invocation inside
    // that module resolves `Kernels` to the local one. Override
    // with `kernels = path::to::Other` when you want to attach the
    // launch method to a different generated `Kernels` (e.g. a
    // second device module in the same crate, or kernels declared
    // outside any device module).
    let kernels = kernels.unwrap_or_else(|| syn::parse_quote!(Kernels));
    Ok(AttrArgs { kernels })
}

fn expand_kernel(func: &ItemFn, args: &AttrArgs) -> syn::Result<TokenStream2> {
    let vis = &func.vis;
    let name = &func.sig.ident;

    // Per-host-param accumulators. The single emitted method takes
    // slices by value (so they can flow through Tier 2 chains and so
    // Tier 1 terminals can return them back). Scalars are by-value.
    // `op_arg_pass` is what we hand to LaunchOp::new from inside the
    // terminal / execute: `&name` for slices, `name` for scalars.
    //
    // Slices get a fresh generic type parameter each (e.g. `__D0`,
    // `__D1`, ...) bounded `: ::claspr::KernelSliceArg<elem>`. This
    // lets the same emitted method accept `DeviceSlice<T>`,
    // `SharedBuffer<T>`, or `USMSlice<T>` interchangeably while
    // keeping the flow-through Output typed precisely.
    let mut host_names: Vec<TokenStream2> = Vec::new();
    let mut method_params: Vec<TokenStream2> = Vec::new();
    let mut arg_types: Vec<TokenStream2> = Vec::new();
    let mut op_arg_pass: Vec<TokenStream2> = Vec::new();
    let mut output_names: Vec<TokenStream2> = Vec::new();
    let mut output_types: Vec<TokenStream2> = Vec::new();
    // `(generic_ident, bound_token_stream)` — populated once per
    // slice param, in source order. Drives the `<__D0, __D1, ...>` +
    // `where`-equivalent inline bounds on every emitted impl block.
    let mut slice_generics: Vec<(TokenStream2, TokenStream2)> = Vec::new();

    for input in &func.sig.inputs {
        let FnArg::Typed(pt) = input else {
            return Err(syn::Error::new(
                input.span(),
                "claspr::kernel does not accept `self` parameters",
            ));
        };
        match classify_param(pt)? {
            ParamRole::Builtin => continue,
            ParamRole::Slice { name: pname, elem } => {
                // Allocate a fresh generic per slice.
                let gid = quote::format_ident!("__claspr_D{}", slice_generics.len());
                let gid_tt: TokenStream2 = quote! { #gid };
                let bound: TokenStream2 = quote! { #gid: ::claspr::KernelSliceArg<#elem> };
                slice_generics.push((gid_tt.clone(), bound));

                host_names.push(pname.clone());
                method_params.push(quote! { #pname: #gid_tt });
                arg_types.push(gid_tt.clone());
                op_arg_pass.push(quote! { &#pname });
                output_names.push(pname.clone());
                output_types.push(gid_tt);
            }
            ParamRole::Image { name: pname, ty } => {
                host_names.push(pname.clone());
                method_params.push(quote! { #pname: #ty });
                arg_types.push(ty.clone());
                op_arg_pass.push(quote! { &#pname });
                output_names.push(pname.clone());
                output_types.push(ty);
            }
            ParamRole::Scalar { name: pname, ty } => {
                host_names.push(pname.clone());
                method_params.push(quote! { #pname: #ty });
                arg_types.push(ty);
                op_arg_pass.push(quote! { #pname });
            }
        }
    }

    // Generic parameter forms used in `impl<...>` / `Op<...>` / fn
    // signature positions. Three flavours:
    //   `<__D0, __D1>`              — for use sites where the generics
    //                                  are already-bound (Op<__D0, __D1>).
    //   `<__D0: K..., __D1: K...>`  — for declarator positions (impl
    //                                  blocks, method generic lists).
    //   `(empty)`                   — when there are no slice params.
    let slice_gen_decl: TokenStream2 = if slice_generics.is_empty() {
        quote! {}
    } else {
        let bounds = slice_generics.iter().map(|(_, b)| b);
        quote! { < #( #bounds ),* > }
    };
    let slice_gen_use: TokenStream2 = if slice_generics.is_empty() {
        quote! {}
    } else {
        let ids = slice_generics.iter().map(|(id, _)| id);
        quote! { < #( #ids ),* > }
    };

    // Single-element tuples need a trailing comma.
    let op_args_tuple_ty = single_or_tuple(&arg_types);
    let op_args_tuple_init = single_or_tuple(&host_names);
    let op_launch_args_tuple = single_or_tuple(&op_arg_pass);

    // Output type / expression — bare for a single slice, tuple for
    // many, `()` for none. Same convention on both terminals
    // (`wait`/`submit`) and the `DeviceOperation::Output`.
    let (output_ty, output_expr) = match output_names.len() {
        0 => (quote! { () }, quote! { () }),
        1 => {
            let n = &output_names[0];
            let t = &output_types[0];
            (quote! { #t }, quote! { #n })
        }
        _ => (
            quote! { ( #(#output_types),* ) },
            quote! { ( #(#output_names),* ) },
        ),
    };

    let kernels_path = &args.kernels;

    // Hidden submodule per kernel: holds the Op struct + impls. The
    // module name keeps the legacy `_op` suffix purely to namespace
    // emissions; users only see `kernels.<name>(...)` and the Op type
    // is doc-hidden.
    let op_mod_ident = quote::format_ident!("__claspr_{}_op", name);
    let kernel_name_lit = name.to_string();

    // Emit ONE method on `Kernels`, named after the kernel. It returns
    // a per-kernel `Op` struct that:
    //
    //   - implements Tier 1 terminals (`.wait(launcher) -> Output`,
    //     `.submit(launcher) -> (Output, Event)`)
    //   - implements builder modifiers (`.after(event)`,
    //     `.after_all(events)`, `.profiled(cb)`)
    //   - implements `DeviceOperation` (Tier 2 chain use)
    //
    // The method calls `kernels.kernel("<name>")` to mint a fresh
    // `cl_kernel` handle owned by the resulting Op. Per-launch
    // `clCreateKernel` keeps `clSetKernelArg` state private to each Op
    // — no possible race even when two chains target the same kernel.
    // Panics on the (extremely rare) `clCreateKernel` OOM because
    // `Kernels::load` already validated every entry point.
    //
    // Because the Op owns its `Kernel` and no longer borrows `&Kernels`,
    // it has **no lifetime parameter** — moving Ops into `tokio::spawn`
    // / threads / `'static` futures is straightforward.
    //
    // Tier 2 use requires `claspr-async` in the user's dep graph (the
    // DeviceOperation impl references it unconditionally). For purely
    // Tier 1 use, the dep is still required to type-check the impl —
    // a price paid once per kernel-crate.
    //
    // `#[allow(clippy::too_many_arguments)]` — the wrapper's arg count
    // is determined by the kernel's declared signature, not user
    // choice, so a per-call `#[allow]` would burden every user.
    Ok(quote! {
        impl #kernels_path {
            #[allow(clippy::too_many_arguments)]
            #vis fn #name #slice_gen_decl (
                &self,
                grid: impl ::claspr::IntoLaunchSpec,
                #(#method_params),*
            ) -> #op_mod_ident::Op #slice_gen_use {
                #op_mod_ident::Op {
                    kernel: self.kernel(#kernel_name_lit),
                    spec: ::claspr::IntoLaunchSpec::into_launch_spec(grid),
                    args: #op_args_tuple_init,
                    deps: ::std::vec::Vec::new(),
                    profile_cb: ::core::option::Option::None,
                }
            }
        }

        #[doc(hidden)]
        #[allow(non_snake_case, non_camel_case_types, unused_imports)]
        pub mod #op_mod_ident {
            use super::*;

            pub struct Op #slice_gen_decl {
                /// Per-launch `cl_kernel` minted by `clCreateKernel`.
                /// Owned and never aliased, so `clSetKernelArg` on it
                /// can't race with any other launch.
                pub kernel: ::claspr::Kernel,
                pub spec: ::claspr::LaunchSpec,
                pub args: #op_args_tuple_ty,
                /// Caller-added wait-list events. Owned so the Op is
                /// `Send` across executor threads — raw `cl_event`
                /// handles aren't, and a borrowed `&Event` can't outlive
                /// its source binding once the Op is moved.
                pub deps: ::std::vec::Vec<::claspr::Event>,
                pub profile_cb: ::core::option::Option<::claspr::ProfileCb>,
            }

            // Op is `Send` automatically — every field is Send. No
            // unsafe impl, no lifetime, no `&Kernels` borrow.

            impl #slice_gen_decl Op #slice_gen_use {
                /// Add a cross-queue dependency. Takes the event by
                /// value because the Op may be moved into an executor
                /// thread; a borrowed `&Event` could outlive the
                /// caller's binding. Chainable.
                pub fn after(mut self, event: ::claspr::Event) -> Self {
                    self.deps.push(event);
                    self
                }

                /// Add multiple wait-list events at once. Chainable.
                pub fn after_all<I>(mut self, events: I) -> Self
                where
                    I: ::core::iter::IntoIterator<Item = ::claspr::Event>,
                {
                    self.deps.extend(events);
                    self
                }

                /// Register a completion callback for profiling info.
                /// Chainable.
                pub fn profiled<F>(mut self, cb: F) -> Self
                where
                    F: ::core::ops::FnOnce(::claspr::Result<::claspr::ProfilingInfo>)
                        + ::core::marker::Send
                        + 'static,
                {
                    self.profile_cb = ::core::option::Option::Some(
                        ::std::boxed::Box::new(cb),
                    );
                    self
                }

                /// Tier 1 non-blocking terminal — enqueue on `launcher`'s
                /// queue and return `(Output, Event)` so the caller can
                /// keep using the buffers and chain via `.after(event)`.
                ///
                /// Panics if any caller-added dep event (from `.after()`
                /// / `.after_all()`) was produced on a different
                /// `Context` than `launcher`'s queue.
                pub fn submit<L>(
                    self,
                    launcher: &L,
                ) -> ::claspr::Result<(#output_ty, ::claspr::Event)>
                where
                    L: ::claspr::Launcher,
                {
                    let Op { kernel, spec, args, deps, profile_cb } = self;
                    // Validate cross-context match for every caller-added
                    // dep. The launcher's context is known here; the
                    // check is two CL info queries + a pointer compare
                    // per dep (cheap), and surfaces mismatches as a
                    // clear panic instead of a cryptic CL_INVALID_CONTEXT
                    // at enqueue time.
                    for ev in &deps {
                        ::claspr::assert_same_context(
                            ev,
                            launcher.cl_queue(),
                            concat!("kernel `", stringify!(#name), "` Op::submit"),
                        );
                    }
                    let #op_args_tuple_init = args;
                    // Hand LaunchOp raw cl_event handles; `deps` (owned
                    // events) stays alive until after the enqueue returns,
                    // at which point OpenCL has retained them internally
                    // for the wait list.
                    let raw_deps: ::std::vec::Vec<::claspr::cl_event> =
                        deps.iter().map(|e| e.get()).collect();
                    let event = ::claspr::LaunchOp::new(
                        launcher,
                        &kernel,
                        spec,
                        #op_launch_args_tuple,
                    )
                    .with_state(raw_deps, profile_cb)
                    .submit()?;
                    ::core::mem::drop(deps);
                    ::core::mem::drop(kernel);
                    ::core::result::Result::Ok((#output_expr, event))
                }

                /// Tier 1 blocking terminal — `submit` then `event.wait`.
                /// Returns the slice arg(s) so the caller can keep using
                /// them.
                pub fn wait<L>(self, launcher: &L) -> ::claspr::Result<#output_ty>
                where
                    L: ::claspr::Launcher,
                {
                    let (out, event) = self.submit(launcher)?;
                    event.wait()?;
                    ::core::result::Result::Ok(out)
                }
            }

            impl #slice_gen_decl ::claspr_async::DeviceOperation for Op #slice_gen_use {
                type Output = #output_ty;

                fn execute(
                    self,
                    ctx: &::claspr_async::ExecutionContext<'_>,
                    chain_deps: ::claspr_async::Deps,
                ) -> ::claspr::Result<(Self::Output, ::claspr_async::Deps)> {
                    let Op { kernel, spec, args, deps, profile_cb } = self;
                    // Validate cross-context match for caller-added deps.
                    // Chain-supplied deps are produced by upstream ops on
                    // the same chain's ExecutionContext, so they're always
                    // from the same Context — no check needed there.
                    for ev in &deps {
                        ::claspr::assert_same_context(
                            ev,
                            ::claspr::Launcher::cl_queue(ctx),
                            concat!("kernel `", stringify!(#name), "` Op::execute"),
                        );
                    }
                    // Merge caller-added (owned Events) with chain-supplied
                    // deps (Arc<Event>) into a single Vec<cl_event>. Both
                    // sources stay alive until after the enqueue.
                    let mut raw_deps: ::std::vec::Vec<::claspr::cl_event> =
                        deps.iter().map(|e| e.get()).collect();
                    for d in &chain_deps {
                        raw_deps.push(d.as_ref().get());
                    }
                    let #op_args_tuple_init = args;
                    let event = ::claspr::LaunchOp::new(
                        ctx,
                        &kernel,
                        spec,
                        #op_launch_args_tuple,
                    )
                    .with_state(raw_deps, profile_cb)
                    .submit()?;
                    ::core::mem::drop(deps);
                    ::core::mem::drop(chain_deps);
                    ::core::mem::drop(kernel);
                    ::core::result::Result::Ok((
                        #output_expr,
                        ::std::vec![::claspr_async::wrap_event(event)],
                    ))
                }
            }
        }
    })
}

/// Tuples with a single element need a trailing comma in Rust. Helper
/// to emit either `(only,)` or `(a, b, c)` based on element count.
/// Returns `()` for an empty list.
fn single_or_tuple(elems: &[TokenStream2]) -> TokenStream2 {
    match elems.len() {
        0 => quote! { () },
        1 => {
            let only = &elems[0];
            quote! { ( #only, ) }
        }
        _ => quote! { ( #(#elems),* ) },
    }
}

enum ParamRole {
    /// Drop: SPIR-V builtin filled in by the runtime.
    Builtin,
    /// Slice param (`#[spirv(cross_workgroup)] &mut [T]`). Becomes a
    /// generic type parameter `D: KernelSliceArg<T>` on the emitted
    /// method + Op, so any of `DeviceSlice<T>` / `SharedBuffer<T>` /
    /// `USMSlice<T>` can flow through.
    Slice {
        name: TokenStream2,
        /// The `T` from `&mut [T]` — used to constrain the generic.
        elem: TokenStream2,
    },
    /// Image param (`&Image!(...)` / `&mut Image!(...)`). Stays
    /// concrete (no generic widening yet — only one image type per
    /// access+format combo).
    Image {
        name: TokenStream2,
        ty: TokenStream2,
    },
    /// Scalar param (no spirv attribute). Passed by value, doesn't
    /// thread through Output.
    Scalar {
        name: TokenStream2,
        ty: TokenStream2,
    },
}

fn classify_param(pt: &PatType) -> syn::Result<ParamRole> {
    let attr = find_spirv_attr(&pt.attrs);
    let kind = attr.as_ref().map(spirv_attr_kind);

    // Anything tagged with a SPIR-V builtin name (global_invocation_id,
    // workgroup_id, local_invocation_id, …) is a runtime-filled input,
    // not a host kernel argument. The complete list lives in
    // `spirv-std::spirv` — rather than enumerate every keyword, we
    // treat everything except `cross_workgroup` as a builtin. This
    // matches the rust-gpu convention where `cross_workgroup` is the
    // *only* attribute that names a host-supplied buffer.
    if matches!(kind, Some(SpirvKind::Builtin)) {
        return Ok(ParamRole::Builtin);
    }

    let pname = match &*pt.pat {
        Pat::Ident(pi) => {
            let id = &pi.ident;
            quote! { #id }
        }
        other => {
            return Err(syn::Error::new(
                other.span(),
                "claspr::kernel parameter pattern must be a plain identifier",
            ));
        }
    };

    if matches!(kind, Some(SpirvKind::CrossWorkgroup)) {
        let elem = slice_element_ty(&pt.ty)?;
        return Ok(ParamRole::Slice { name: pname, elem });
    }
    if let Some(info) = classify_image_param(&pt.ty) {
        let access = info.access;
        let format = info.format;
        return Ok(ParamRole::Image {
            name: pname,
            ty: quote! { ::claspr::Image2D<#access, #format> },
        });
    }
    let t = &pt.ty;
    Ok(ParamRole::Scalar {
        name: pname,
        ty: quote! { #t },
    })
}

/// Pull the element type out of `&[T]` / `&mut [T]`. Reused by both
/// the Tier 1 wrapper translation and Tier 2's owned-arg type.
fn slice_element_ty(ty: &Type) -> syn::Result<TokenStream2> {
    let Type::Reference(TypeReference { elem, .. }) = ty else {
        return Err(syn::Error::new(
            ty.span(),
            "expected a reference type (`&[T]` or `&mut [T]`) for a #[spirv(cross_workgroup)] \
             parameter; other shapes are not yet supported by claspr::kernel",
        ));
    };
    let Type::Slice(TypeSlice { elem: inner, .. }) = &**elem else {
        return Err(syn::Error::new(
            elem.span(),
            "expected a slice type `[T]` after the reference; other shapes are not yet supported \
             by claspr::kernel",
        ));
    };
    Ok(quote! { #inner })
}

fn find_spirv_attr(attrs: &[Attribute]) -> Option<Attribute> {
    attrs.iter().find(|a| a.path().is_ident("spirv")).cloned()
}

enum SpirvKind {
    /// `#[spirv(cross_workgroup)]` — host-supplied buffer; translate type.
    CrossWorkgroup,
    /// Anything else (`#[spirv(global_invocation_id)]`, `workgroup`, …)
    /// — drop from host signature.
    Builtin,
}

fn spirv_attr_kind(attr: &Attribute) -> SpirvKind {
    // We want to know whether the inner meta starts with `cross_workgroup`.
    // Use the parse_args-as-token-stream path so we don't have to enumerate
    // every spirv attribute syn might know about.
    let tokens = attr.meta.require_list().ok().map(|l| l.tokens.clone());
    let Some(tokens) = tokens else {
        return SpirvKind::Builtin;
    };
    let first_ident = tokens
        .into_iter()
        .find_map(|tt| match tt {
            proc_macro2::TokenTree::Ident(i) => Some(i.to_string()),
            _ => None,
        })
        .unwrap_or_default();
    if first_ident == "cross_workgroup" {
        SpirvKind::CrossWorkgroup
    } else {
        SpirvKind::Builtin
    }
}

/// Parsed `Image!(...)` parameter info: the access-mode and format
/// type paths to splice into the generated `&Image2D<A, F>` arg.
struct ImageInfo {
    access: TokenStream2,
    format: TokenStream2,
}

/// Recognise `&Image!(...)` / `&mut Image!(...)` and parse the
/// macro's token list to pick the matching claspr `Image2D<A, F>`
/// host-side type.
///
/// Mapping:
///
/// - `access=` token (if present) wins: `read_only` → `ReadOnly`,
///   `write_only` → `WriteOnly`, `read_write` → `ReadWrite`.
/// - Otherwise the default is `ReadWrite` — matching rust-gpu's
///   unspecified-access behaviour (OpenCL treats it as both
///   readable and writable). The host-side reference mutability
///   (`&` vs `&mut`) is intentionally NOT used to pick access, so
///   that today's `&mut Image!(2D, type=u32, ...)` kernels keep
///   accepting the existing `Image2DRgba8` allocator (which is
///   `Image2D<ReadWrite, ...>`).
/// - `format=<name>` token (if present) wins for format selection:
///   the name is taken as a `::claspr::image::format::<name>` ZST.
/// - Otherwise, `type=u32` / `type=f32` / `type=i32` pick sensible
///   defaults: `R8G8B8A8Uint` / `R32G32B32A32Float` / `R8G8B8A8Sint`.
/// - Otherwise (no `type=` either) the default is `R8G8B8A8Uint`
///   — same as the legacy `Image2DRgba8` alias.
///
/// Returns `None` if `ty` doesn't look like an `Image!(...)` ref.
fn classify_image_param(ty: &Type) -> Option<ImageInfo> {
    let Type::Reference(TypeReference { elem, .. }) = ty else {
        return None;
    };
    let Type::Macro(TypeMacro { mac }) = &**elem else {
        return None;
    };
    if !mac.path.is_ident("Image") {
        return None;
    }
    let (access_tok, format_tok, type_tok) = parse_image_tokens(mac.tokens.clone());

    let access = match access_tok.as_deref() {
        Some("read_only") => quote! { ::claspr::ReadOnly },
        Some("write_only") => quote! { ::claspr::WriteOnly },
        Some("read_write") | None => quote! { ::claspr::ReadWrite },
        Some(other) => {
            // Unknown access keyword — fall back to ReadWrite and
            // let the runtime sort it out. We could span-error here
            // but tolerating unknown tokens keeps the macro forward-
            // compatible with future rust-gpu Image! grammar.
            let _ = other;
            quote! { ::claspr::ReadWrite }
        }
    };

    let format = if let Some(fname) = format_tok {
        let ident = quote::format_ident!("{}", fname);
        quote! { ::claspr::image::format::#ident }
    } else {
        match type_tok.as_deref() {
            Some("f32") => quote! { ::claspr::image::format::R32G32B32A32Float },
            Some("i32") => quote! { ::claspr::image::format::R8G8B8A8Sint },
            // `u32` and the catch-all both map to the RGBA8 uint
            // format — same as the legacy `Image2DRgba8` alias.
            _ => quote! { ::claspr::image::format::R8G8B8A8Uint },
        }
    };

    Some(ImageInfo { access, format })
}

/// Scan an `Image!(...)` token list for `access=<ident>`,
/// `format=<ident>`, and `type=<ident>` key/value pairs. Tokens are
/// comma-separated; standalone idents (`2D`, `3D`, …) are ignored.
fn parse_image_tokens(tokens: TokenStream2) -> (Option<String>, Option<String>, Option<String>) {
    let mut access = None;
    let mut format = None;
    let mut type_ = None;
    let tts: Vec<proc_macro2::TokenTree> = tokens.into_iter().collect();
    let mut i = 0;
    while i < tts.len() {
        // Look for `<ident> = <ident>` triples.
        if let (
            Some(proc_macro2::TokenTree::Ident(key)),
            Some(proc_macro2::TokenTree::Punct(eq)),
            Some(proc_macro2::TokenTree::Ident(val)),
        ) = (tts.get(i), tts.get(i + 1), tts.get(i + 2))
            && eq.as_char() == '='
        {
            let k = key.to_string();
            let v = val.to_string();
            match k.as_str() {
                "access" => access = Some(v),
                "format" => format = Some(v),
                "type" => type_ = Some(v),
                _ => {}
            }
            i += 3;
            continue;
        }
        i += 1;
    }
    (access, format, type_)
}
