//! End-to-end example for claspr's stage-3 single-source pipeline.
//!
//! - The kernel function lives in `src/kernels.rs`, marked with
//!   `#[claspr::kernel]`. The proc-macro turns it into a host launch
//!   wrapper for this crate's compilation.
//! - The build script (`build.rs`) calls
//!   `claspr_build::compile_from_host("src/kernels.rs")` to extract
//!   the same source into a generated kernel sub-crate, compile it
//!   via `spirv-builder`, and emit the [`compiled::Kernels`] struct.
//!
//! Tests at `tests/end_to_end.rs` exercise the full path.

/// The host-side launch wrappers, generated by the
/// `#[claspr::kernel]` proc-macro on every entry-point function.
pub mod kernels;

/// The build-script-generated kernel handles + SPV bytes.
pub mod compiled {
    include!(concat!(env!("OUT_DIR"), "/collatz_kernels.rs"));
}
